### ISSUE TITLE
Why is there a need for a web server for execQuery and  checkConnection

### ISSUE THREAD

**Issue by deepanshu2506** [amandesai01/SQLtoJSON#1]
It would be more efficient and resilient if that dependancy goes down .
I think I have a solution..
If you say I could work on that.

**Comment by amandesai01** [comment]
This is because, aim is to host that server somewhere and then, provide it as a microservice. And pypackage will be responsible for communicating with it. So, 1 server instance and multiple package instance. This is a part of further development. Currently, it will but not efficiently support concurrency.

**Comment by deepanshu2506** [comment]
ohhh now I get it. Nice thought..
